name: MachineLearningTutorialUdacity

channels:
  - conda-forge
  - rdkit
  - anaconda
   
dependencies:
  - numpy
  - nlp
  - pandas
  - pip
  - python=3.8
  - rdkit
  - matplotlib
  - seaborn
  - scikit-learn
  - tensorflow
